---
##
# Import variable definitions and defaults
##
- name: IMPORT_TASKS | Setup Variable definitions / defaults
  import_tasks: setup-variables.yml

##
# Set up the OS based on family
##
- name: IMPORT_TASKS | Setup percona mysql for OS
  import_tasks: "setup-Debian.yml"
  when:
    - ansible_facts['os_family'] == 'Debian'

- name: IMPORT_TASKS | Set up xtrabackup
  import_tasks: "configure-xtrabackup.yml"
