---
#
# Default OS specific variable definitions / defaults
#
- block:
  - name: INCLUDE_VARS | OS specific vars
    include_vars: "{{ ansible_facts['os_family'] }}.yml"

  - name: FACTS - Define Percona MySQL version
    set_fact:
      percona_xtrabackup_mysql_version_abs: "{{ percona_xtrabackup_mysql_version | int | abs }}"
    when: percona_xtrabackup_mysql_version_abs is not defined

  - name: FACTS - Define repository for Percona MySQL
    set_fact:
      percona_xtrabackup_repository: "{{ __percona_xtrabackup_repository }}"
    when: percona_xtrabackup_repository is not defined

  - name: FACTS - Define package dependencies for Percona MySQL
    set_fact:
      percona_xtrabackup_package_dependencies: "{{ __percona_xtrabackup_package_dependencies | list }}"
    when: percona_xtrabackup_package_dependencies is not defined

  - name: FACTS - Define command to enable Percona MySQL 8 repository
    set_fact:
      percona_xtrabackup_enable_repository: "{{ __percona_xtrabackup_8_enable_repository }}"
    when: percona_xtrabackup_enable_repository is not defined and percona_xtrabackup_mysql_version_abs == "8"

  - name: FACTS - Define Percona MySQL 8 packages
    set_fact:
      percona_xtrabackup_package: "{{ __percona_xtrabackup_8_package | list }}"
    when: percona_xtrabackup_package is not defined and percona_xtrabackup_mysql_version_abs == "8"

  - name: FACTS - Define Percona XtraBackup days to keep
    set_fact:
      percona_xtrabackup_days_to_keep: "{{ percona_xtrabackup_days_to_keep | int - 1 }}"

  - name: FACTS - Define Percona XtraBackup backup command
    set_fact:
      percona_xtrabackup_backup_command: "{{ percona_xtrabackup_dir }}/backup.sh >> {{ percona_xtrabackup_dir }}/backup.log 2>&1"

  - name: FACTS - Define Percona XtraBackup cleanup command
    set_fact:
      percona_xtrabackup_cleanup_command: "{{ percona_xtrabackup_dir }}/clean.sh >> {{ percona_xtrabackup_dir }}/clean.log 2>&1"

  - name: FACTS - Define Percona binlog backup command
    set_fact:
      percona_xtrabackup_binlog_backup_command: "/usr/bin/rsync --size-only --delete-after -av --stats {{ percona_xtrabackup_binary_log_dir }}/ {{ percona_xtrabackup_dir }}/binlogs/ >> {{ percona_xtrabackup_dir }}/binlogs.log 2>&1"

  when: percona_xtrabackup_enabled
