---
#
# Setup all required packages
#
- block:
    - name: APT | Updating the apt cache
      apt:
        update_cache: yes

    - name: APT | Install package dependencies
      apt:
        name: "{{ percona_xtrabackup_package_dependencies }}"
        state: present

    - name: APT | Install the Percona MySQL repository
      apt:
        deb: "{{ percona_xtrabackup_repository }}"
      when: percona_xtrabackup_repository is defined

    - name: APT | Updating the apt cache after adding the release repository
      apt:
        update_cache: yes

    - name: COMMAND | Enable the Percona MySQL repository
      command: "{{ percona_xtrabackup_enable_repository }}"
      when: percona_xtrabackup_enable_repository is defined
      changed_when: False

    - name: APT | Make sure percona xtrabackup is installed (if configured)
      apt:
        name: "{{ percona_xtrabackup_package }}"
        state: "{{ percona_xtrabackup_packages_mode }}"

  when: percona_xtrabackup_enabled
